export const AppConfig = Object.freeze({
  appName: "Heineken - Painel de Indicadores YTD",
  data: Object.freeze({
    provider: "jsonFile",
    providers: Object.freeze({
      jsonFile: Object.freeze({
        url: "./public/dashboard-data.json",
        fallbackUrls: Object.freeze(["./dashboard-data.json"]),
        request: Object.freeze({
          cache: "no-cache",
          credentials: "same-origin",
        }),
      }),
      api: Object.freeze({
        endpoint: "",
        request: Object.freeze({
          cache: "no-cache",
          credentials: "same-origin",
        }),
      }),
      graph: Object.freeze({
        endpoint: "",
        request: Object.freeze({
          cache: "no-cache",
          credentials: "same-origin",
        }),
        scopes: Object.freeze([]),
      }),
    }),
  }),
  dashboard: Object.freeze({
    defaultIndicatorId: "ocupacao",
    defaultTempoView: "bar",
  }),
  charts: Object.freeze({
    renderer: "canvas",
    theme: null,
    ids: Object.freeze({
      indicator: "selected-indicator",
      dailyTime: "tempo-diario",
      monthlyTime: "tempo-mensal",
      accuracy: "acuracidade-diaria",
      inventory: "inventario-diario",
      deviation: "desvios-progressao",
      audit: "auditoria-progressao",
    }),
    format: Object.freeze({
      locale: "pt-BR",
      currency: "BRL",
      emptyValue: "—",
      thousandSuffix: "k",
      percentSuffix: "%",
      gainPrefix: "+",
      percentagePointSuffix: " p.p.",
    }),
    text: Object.freeze({
      result: "Resultado",
      target: "Meta",
      targetUpper: "META",
      dailyTimeValue: "Tempo",
      accuracy: "Acuracidade",
      execution: "Execução",
      monthlyDeviation: "No mês",
      accumulated: "Acumulado",
      score5s: "Score 5S",
      monthlyGain: "Ganho no mês",
      targetDailyTime: "META 2:00",
      targetMonthlyTime: "META 8:00",
      targetAccuracy: "META 95%",
      targetInventory: "META 95%",
      targetAudit: "META 100%",
    }),
    colors: Object.freeze({
      brand: "var(--brand)",
      brandGlow: "var(--brand-glow)",
      brandDeep: "var(--brand-deep)",
      gold: "var(--gold)",
      border: "var(--border)",
      card: "var(--card)",
      muted: "var(--muted)",
      mutedForeground: "var(--muted-foreground)",
      destructive: "var(--destructive)",
      destructiveMixed: "var(--chart-destructive-mixed)",
      white: "#ffffff",
      transparent: "transparent",
    }),
    gradients: Object.freeze({
      brandBar: Object.freeze([
        Object.freeze({ offset: 0, color: "brandGlow" }),
        Object.freeze({ offset: 1, color: "brandDeep" }),
      ]),
      brandArea: Object.freeze([
        Object.freeze({ offset: 0, color: "brandGlow", opacity: 0.7 }),
        Object.freeze({ offset: 1, color: "brand", opacity: 0.05 }),
      ]),
      softArea: Object.freeze([
        Object.freeze({ offset: 0, color: "brandGlow", opacity: 0.6 }),
        Object.freeze({ offset: 1, color: "brand", opacity: 0.05 }),
      ]),
      accumulatedArea: Object.freeze([
        Object.freeze({ offset: 0, color: "brandGlow", opacity: 0.5 }),
        Object.freeze({ offset: 1, color: "brand", opacity: 0.03 }),
      ]),
    }),
    style: Object.freeze({
      gridDash: "3 6",
      metaDash: "6 6",
      axisFontSize: 12,
      smallAxisFontSize: 11,
      metaLineWidth: 2,
      lineWidth: 2,
      strongLineWidth: 3,
      smooth: true,
      barRadius: Object.freeze([10, 10, 4, 4]),
      monthlyBarRadius: Object.freeze([8, 8, 2, 2]),
      smallBarRadius: Object.freeze([6, 6, 0, 0]),
      barMaxWidth: Object.freeze({
        indicator: 48,
        dailyTime: 54,
        monthlyTime: 44,
      }),
      barWidth: Object.freeze({
        progression: 26,
      }),
      domains: Object.freeze({
        dailyTimePadding: 20,
        accuracy: Object.freeze([80, 100]),
        inventory: Object.freeze([0, 100]),
        auditLevel: Object.freeze([70, 100]),
        auditGain: Object.freeze([0, 20]),
      }),
      grid: Object.freeze({
        top: 12,
        right: 20,
        bottom: 24,
        left: 6,
        compactRight: 10,
        containLabel: true,
      }),
      dotRadius: 4,
      largeDotRadius: 5,
    }),
  }),
});
